session_name: {{ cookiecutter.__project_slug }}
windows:
  - window_name: recon
    layout: main-horizontal
  - window_name: shell
  - window_name: notes
    panes:
      - nvim steps.md
  - window_name: vpn
    panes:
      - sudo openvpn ~/universal.ovpn
    window_index: 9

