session_name: {{ cookiecutter.__project_slug }}
windows:
  - window_name: main
    layout: main-horizontal
  - window_name: recon
  - window_name: vpn
    panes:
      - sudo openvpn ~/universal.ovpn
    window_index: 9

